#   Section: Organizations
#   - Phần này để khai báo các organizations

Organizations:


  - &OrdererOrg

    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/example.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

    OerdererEnpoints:
      - orderer.example.com:7050

  - &Producer

    Name: Producer
    ID: ProducerMSP
    MSPDir: ../organizations/peerOrganizations/producer.example.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ProducerMSP.admin', 'ProducerMSP.peer', 'ProducerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ProducerMSP.admin', 'ProducerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ProducerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ProducerMSP.peer')"

    AnchorPeers:
      - Host: peer0.producer.example.com
        Port: 7051

  - &Manufacturer

    Name: Manufacturer
    ID: ManufacturerMSP
    MSPDir: ../organizations/peerOrganizations/manufacturer.example.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ManufacturerMSP.peer')"

    AnchorPeers:
      - Host: peer0.manufacturer.example.com
        Port: 7052

  - &Deliverer

    Name: Deliverer
    ID: DelivererMSP
    MSPDir: ../organizations/peerOrganizations/deliverer.example.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DelivererMSP.admin', 'DelivererMSP.peer', 'DelivererMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DelivererMSP.admin', 'DelivererMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DelivererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DelivererMSP.peer')"

    AnchorPeers:
      - Host: peer0.deliverer.example.com
        Port: 7053

  - &Retailer

    Name: Retailer
    ID: RetailerMSP
    MSPDir: ../organizations/peerOrganizations/retailer.example.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RetailerMSP.admin', 'RetailerMSP.peer', 'RetailerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RetailerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RetailerMSP.peer')"

    AnchorPeers:
      - Host: peer0.retailer.example.com
        Port: 7054



#       Section: Capabilities
#       -


Capabilities:

  Channel: &ChannelCapabilities
    V2_0: True
  Application: &ApplicationCapabilities
    V2_0: True

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

#       Section: Orderer
#

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  Addresses:
    - orderer.example.com:7050

  EtcdRaft:
    Consenters:
    - Host: orderer.example.com
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99MB
    PreferredMaxBytes: 512 KB

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

    BlockValidation:
        Type: ImplicitMeta
        Rule: "ANY Writers"

        
